App/urls.py
from django.urls import path
from App.views import index
from .views import DesignLoginView, register, DeleteRequestView, admin_category_add, category_list, AdminCategoryDelete, \
    request_all, ChangeStatusCompleted, ChangeStatusAcceptWork
from .views import DesignLogoutView
from .views import RegisterDoneView, RegisterUserView
from .views import profile
from .views import profile_request_add
from .views import other_page


app_name = 'App'

urlpatterns = [
    path('', index, name='index'),
    path('accounts/login', DesignLoginView.as_view(), name='login'),
    path('accounts/logout/', DesignLogoutView.as_view(), name='logout'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', register, name='register'),
    path('accounts/profile/', profile, name='profile'),
    # path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/add/', profile_request_add, name='profile_request_add'),
    # path('accounts/profile/delete/<int:id>/', profile_request_delete, name='profile_request_delete'),
    path('applications/delete/<int:pk>/', DeleteRequestView.as_view(), name='profile_request_delete'),
    path('category/add/', admin_category_add, name='admin_category_add'),
    path('category/delete/<int:id>', AdminCategoryDelete.as_view(), name='admin_category_delete'),
    path('category/list/', category_list, name='category_list'),
    path('request/all/', request_all, name='request_all'),
    path('change/status/completed/<int:id>/', ChangeStatusCompleted.as_view(), name='change_status_completed'),
    path('change/status/accept/work/<int:id>/', ChangeStatusAcceptWork.as_view(), name='change_status_accept_work'),
    # path('<int:pk>/', rubric, name='rubric'),
    # path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    # path('<str:page>/', other_page, name='other'),
]

Design/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve

from django.conf.urls.static import static

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('App.urls', namespace='')),
]

if settings.DEBUG:
   urlpatterns.append(path('static/<path:path>', never_cache(serve)))
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/templates/main/index.html
{% extends "layout/main.html" %}

{% block content %}
  <h2>Последние 4 заявки</h2>
  {% for request in request_list %}
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="{{request.image.url}}" class="card-img" alt="{{request_list.title}}">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Название: {{request.title}}</h5>
            <h5 class="card-title">Категория: {{request.category}}</h5>
            <p class="card-text">Дата: {{request.created_at}}</p>
          </div>
        </div>
      </div>
    </div>
  {% empty %}
    <p>Нет заявок</p>
  {% endfor %}
{% block body %} <p>Количество заявок, находящихся в статусе «Принято в работу»: {{ request_count }}</p> {% endblock body %}
{% endblock %}

App/templates/main/login.html
{% extends "layout/main.html" %}
{% load bootstrap4 %}
{% block title %} Вход {% endblock %}
{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
   {% csrf_token %}
   {% bootstrap_form form layout='horizontal' %}
   <input type="hidden" name="next" value="{{ next }}">
   {% buttons submit='Войти' %} {% endbuttons %}
</form>
{% endif %}
{% endblock %}

App/templates/main/logout.html
{% extends "layout/main.html" %}


{% block title %} Выход {% endblock %}


{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

App/templates/main/profile.html
{% extends "layout/main.html" %}
{% load bootstrap4 %}
{% block title %} Профиль пользователя {% endblock %}
{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }} </p>
{% else %}
<p>Здравствуйте! </p>
{% endif %}
<button type="button" class="btn btn-primary"><a href="{% url 'App:profile_request_add' %}" style="color: white; text-decoration: none;">Добавить заявку</a></button>
<h3>Ваши заявки</h3>

<h5>Статус заявки:</h5>
<form method="GET">
    <select class="dropdown-item" name="status">
        <option value="">Все</option>
        <option value="Новая">Новая</option>
        <option value="Принято в работу">Принято в работу</option>
        <option value="Выполнено">Выполнено</option>
    </select>
    <button type="submit" class="btn btn-primary">Фильтровать</button>
</form>

{% if status == 'Новая' %}
    {% for request in request_list %}
    {% if request.status == 'Новая' %}
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Название: {{request.title}}</h5>
                    <p class="card-text">Категория: {{request.category}}</p>
                    <p class="card-text">Дата: {{request.created_at}}</p>
                    <p class="card-text">Описание: {{request.content}}</p>
                    <p class="card-text">Статус: {{request.status}}</p>
                </div>
                <button type="button" class="btn btn-danger"><a href="{% url 'App:profile_request_delete' pk=request.id%}" style="color: white; text-decoration: none;">Удалить заявку</a></button>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}

{% elif status == 'Принято в работу' %}
    {% for request in request_list %}
    {% if request.status == 'Принято в работу' %}
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Название: {{request.title}}</h5>
                    <p class="card-text">Категория: {{request.category}}</p>
                    <p class="card-text">Дата: {{request.created_at}}</p>
                    <p class="card-text">Описание: {{request.content}}</p>
                    <p class="card-text">Статус: {{request.status}}</p>
                </div>
                <button type="button" class="btn btn-danger"><a href="{% url 'App:profile_request_delete' pk=request.id%}" style="color: white; text-decoration: none;">Удалить заявку</a></button>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}

{% elif status == 'Выполнено' %}
    {% for request in request_list %}
    {% if request.status == 'Выполнено' %}
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Название: {{request.title}}</h5>
                    <p class="card-text">Категория: {{request.category}}</p>
                    <p class="card-text">Дата: {{request.created_at}}</p>
                    <p class="card-text">Описание: {{request.content}}</p>
                    <p class="card-text">Статус: {{request.status}}</p>
                </div>
                <button type="button" class="btn btn-danger"><a href="{% url 'App:profile_request_delete' pk=request.id%}" style="color: white; text-decoration: none;">Удалить заявку</a></button>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}

{% else %}
    {% for request in request_list %}
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Название: {{request.title}}</h5>
                    <p class="card-text">Категория: {{request.category}}</p>
                    <p class="card-text">Дата: {{request.created_at}}</p>
                    <p class="card-text">Описание: {{request.content}}</p>
                    <p class="card-text">Статус: {{request.status}}</p>
                </div>
                <button type="button" class="btn btn-danger"><a href="{% url 'App:profile_request_delete' pk=request.id%}" style="color: white; text-decoration: none;">Удалить заявку</a></button>
            </div>
        </div>
    </div>
    {% endfor %}
{% endif %}

{% endblock %}

App/templates/main/profile_request_add.html
{% extends "layout/main.html" %}


{% load bootstrap4 %}


{% block title %} Добавление заявки {% endblock %}


{% block content %}
<h2>Добавление заявки</h2>
<form method="post" enctype="multipart/form-data">
   {% csrf_token %}
   {% bootstrap_form form layout='horizontal' %}
   {% buttons submit='Добавить' %} {% endbuttons %}
</form>
{% endblock %}

App/templates/main/profile_request_delete.html
{% extends "layout/main.html" %}


{% load bootstrap4 %}


{% block title %} Удаление Заявки {% endblock %}


{% block content %}
<h2>Удаление заявки {{ app.title }}</h2>
 {% if object.status == 'Новая' %}
   <p>Вы уверены, что хотите удалить эту заявку?</p>
      <form method="post">
         {% csrf_token %}
         {% buttons submit='Удалить' %} {% endbuttons %}
      </form>
      {% else %}
             <p>Нельзя удалять заявки со статусом, отличным от "Новая"</p>
      {% endif %}
{% endblock %}

App/templates/main/register_done.html
{% extends "layout/main.html" %}


{% block title %} Регистрация завершена {% endblock %}


{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо для активации</p>
{% endblock %}

App/templates/main/register_user.html
{% extends "layout/main.html" %}


{% load bootstrap4 %}


{% block title %} Регистрация {% endblock %}


{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
   {% csrf_token %}
   {% bootstrap_form form layout='horizontal' %}
   {% buttons submit='Зарегистрироваться' %} {% endbuttons %}
</form>
{% endblock %}

App/templates/main/request_list.html
{% extends "layout/main.html" %}

{% block content %}
    <h1>Мои заявки</h1>
    {% if request_list %}
    <label for="status_filter">Фильтр по статусу:</label>
        <select name="status_filter" id="status_filter" onchange="location.href = '{% url 'main:appli_list' %}?stas=' + this.value;">
            <option value="all" {% if status_filter == 'all' %}selected{% endif %}>Все</option>
            <option value="Н" {% if status_filter == 'Н' %}selected{% endif %}>Новые</option>
            <option value="П" {% if status_filter == 'П' %}selected{% endif %}>В работе</option>
            <option value="В" {% if status_filter == 'В' %}selected{% endif %}>Выполненные</option>
        </select>

    <ul>
      {% for request in request_list %}
      <li>
            <p><strong>Дата создания:</strong> {{request.created_at}}</p>
            <p><strong>Название:</strong> {{request.title}}</p>
            <p><strong>Описание:</strong> {{request.content}}</p>
            <p><strong>Категория:</strong> {{request.category}}</p>
            <p><strong>Статус заявки:</strong> {{request.status}}</p>
            <nav class="col-md-auto nav flex-column">
                <a class="nav-link root" href="{% url 'App:profile_request_delete' pk=app.id %}">Удалить заявку</a>
            </nav>
            <hr>

      </li>
      {% endfor %}
    </ul>
    {% else %}
    <label for="status_filter">Фильтр по статусу:</label>
        <select name="status_filter" id="status_filter" onchange="location.href = '{% url 'App:request_list' %}?status=' + this.value;">
            <option value="all" {% if status_filter == 'all' %}selected{% endif %}>Все</option>
            <option value="Н" {% if status_filter == 'Н' %}selected{% endif %}>Новые</option>
            <option value="П" {% if status_filter == 'П' %}selected{% endif %}>В работе</option>
            <option value="В" {% if status_filter == 'В' %}selected{% endif %}>Выполненные</option>
        </select>
<h2> у вас нету заявок</h2>
{% endif %}
{% endblock %}

App/templates/main/rubric.html
{% extends "layout/main.html" %}


{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}


{% block title %}{{ rubric }}{% endblock %}


{% block searchform %}
{% endblock %}


{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>
<div class="container-fluid mb-2">
   <div class="row">
       <div class="col">&nbsp;</div>
       <form class="col-md-auto form-inline">
           {% bootstrap_form form show_label=False %}
           {% bootstrap_button content='Искать' button_type='submit' %}
       </form>
   </div>
</div>
{% if bbs %}
<ul class="list-unstyled">
   {% for Request in bbs %}
   <li class="media my-5 p-3 border">
       {% url 'App:detail' rubric_pk=rubric.pk pk=Request.pk as url %}
       <a href="{{ url }}{{ all }}">
           {% if Request.image %}
           <img class="mr-3" src="{% thumbnail Request.image 'default' %}">
           {% else %}
           <img class="mr-3" src="{% static 'main/empty.jpg' %}">
           {% endif %}
       </a>
       <div class="media-body">
           <h3><a href="{{ url }}{{ all }}">{{ Request.title }}</a></h3>
           <h3><a href="{{ url }}{{ all }}">{{ Request.category }}</a></h3>
           <p class="text-right font-italic">{{ Request.created_at }}</p>
           <button type="button" class="btn btn-primary"><a href="{% url 'App:profile_request_delete' %}" style="color: white; text-decoration: none;">Удалить заявку</a></button>
       </div>
   </li>
   {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}