App/urls.py
from django.urls import path
from App.views import index
from .views import DesignLoginView, register, DeleteRequestView, admin_category_add, category_list, AdminCategoryDelete, \
    request_all, ChangeStatusCompleted, ChangeStatusAcceptWork
from .views import DesignLogoutView
from .views import RegisterDoneView, RegisterUserView
from .views import profile
from .views import profile_request_add
from .views import other_page


app_name = 'App'

urlpatterns = [
    path('', index, name='index'),
    path('accounts/login', DesignLoginView.as_view(), name='login'),
    path('accounts/logout/', DesignLogoutView.as_view(), name='logout'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', register, name='register'),
    path('accounts/profile/', profile, name='profile'),
    # path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/add/', profile_request_add, name='profile_request_add'),
    # path('accounts/profile/delete/<int:id>/', profile_request_delete, name='profile_request_delete'),
    path('applications/delete/<int:pk>/', DeleteRequestView.as_view(), name='profile_request_delete'),
    path('category/add/', admin_category_add, name='admin_category_add'),
    path('category/delete/<int:id>', AdminCategoryDelete.as_view(), name='admin_category_delete'),
    path('category/list/', category_list, name='category_list'),
    path('request/all/', request_all, name='request_all'),
    path('change/status/completed/<int:id>/', ChangeStatusCompleted.as_view(), name='change_status_completed'),
    path('change/status/accept/work/<int:id>/', ChangeStatusAcceptWork.as_view(), name='change_status_accept_work'),
    # path('<int:pk>/', rubric, name='rubric'),
    # path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    # path('<str:page>/', other_page, name='other'),
]

Design/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve

from django.conf.urls.static import static

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('App.urls', namespace='')),
]

if settings.DEBUG:
   urlpatterns.append(path('static/<path:path>', never_cache(serve)))
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/templates/layout/main.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
  <title>{% block title %} Главная {% endblock %} - Электронная доска объявлений </title>
</head>
<body>
<div class="container-fluid">
  <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3  bg-white border-bottom box-shadow">
    <h5 class="mr-md-auto p-2"><a class="nav-link root" href="{% url 'App:index'  %}">Design.pro</a></h5>
    {% if user.is_authenticated %}
    <div class="nav-item dropdown">
       <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Профиль</a>
       <div class="dropdown-menu">
           <a class="dropdown-item" href="{% url 'App:profile' %}">Мои заявки</a>
           {% if user.is_staff %}
            <a class="dropdown-item" href="{% url 'App:category_list' %}">Список категорий</a>
           <a class="dropdown-item" href="{% url 'App:request_all' %}">Список заявок</a>
           {% endif %}
           <a class="dropdown-item" href="{% url 'App:logout' %}">Выйти</a>
       </div>
    </div>
    {% else %}
    <a class="p-2 text-dark" href="{% url 'App:register' %}">Регистрация</a>
    <a class="p-2 text-dark" href="{% url 'App:login' %}">Вход</a>
    {% endif %}
  </div>
    <div class="row">
      <div class="container">
      {% bootstrap_messages %}
      {% block content %}
      {% endblock %}
      </div>
    </div>

  <footer class="mt-3 border-top">
  </footer>
</div>


</body>
</html>